# Generated by Django 5.0.4 on 2024-06-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth0_user_id', models.CharField(db_comment='Auth0ユーザーID', max_length=100)),
                ('first_name', models.CharField(db_comment='名', max_length=150)),
                ('last_name', models.CharField(db_comment='姓', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新日時')),
            ],
            options={
                'db_table_comment': 'ユーザー',
            },
        ),
    ]
